### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by compyy** [lcristianiim/estimote-beacon-getter#2]
Change following.

/home/pi/estimote-beacon-getter-master/lib/telemetry.js:212
    temperature = temperatureRawValue / 16.0;

to

/home/pi/estimote-beacon-getter-master/lib/telemetry.js:212
    var temperature = temperatureRawValue / 16.0;

**Comment by lcristianiim** [comment]
Good job @compyy :+1: 
Fixed by 62d0d867a32a4bbf9c51c331d7a0cbba6cac2db8
